alms/alms/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
# from django.contrib.auth.forms import AdminPasswordChangeForm

urlpatterns = [
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^employee/',include('employee.urls',namespace='employee')),
    url(r'^leave/',include('leave.urls',namespace='leave')),
    url(r'^holiday/',include('holiday.urls',namespace='holiday')),
    url(r'^accounts/password/reset/$', auth_views.password_reset,{'template_name': 'accounts/password_reset_form.html'}, name='reset_password'),
    url(r'^accounts/password/reset/done/$',auth_views.password_reset_done,{'template_name': 'accounts/password_reset_done.html'}, name='password_reset_done'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.password_reset_confirm,{'template_name': 'accounts/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$',auth_views.password_reset_complete,{'template_name': 'accounts/password_reset_complete.html'}, name='password_reset_complete'),
]

alms/leave/api/urls.py
from django.conf.urls import url
from .views import LeaveRulesRudView, LeaveRulesAPIView

urlpatterns = [
    url(r'^$',LeaveRulesAPIView.as_view(),name='post-create'),
    url(r'^(?P<pk>\d+)/$',LeaveRulesRudView.as_view(),name='post-rud')
]

alms/leave/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'leave'

urlpatterns = [
    url(r'rules/list/$',views.List.as_view(),name='list'),
    url(r'rules/detail/(?P<pk>\d+)/$',views.LeaveRulesDetail.as_view(),name='detail'),
    url(r'rules/create/$',views.LeaveRulesCreateView.as_view(),name='create'),
    url(r'rules/update/(?P<pk>\d+)/$',views.LeaveRulesUpdateView.as_view(),name='update'),
    url(r'rules/delete/(?P<pk>\d+)/$',views.LeaveRulesDeleteView.as_view(),name='delete'),
    url(r'apply/$',views.LeaveApplyCreateView.as_view(),name='apply'),
    url(r'applied/$',views.LeaveAppliedListView.as_view(),name='applied'),
    url(r'applied/(?P<username>[-\w]+)/$',views.LeaveAppliedUserListView.as_view(),name='applied_leave'),
    url(r'draft/(?P<username>[-\w]+)/$',views.LeaveDraftListView.as_view(),name='draft'),
    url(r'apply/update/(?P<pk>\d+)/$',views.LeaveApplyUpdateView.as_view(),name='apply_update'),
    url(r'apply/delete/(?P<pk>\d+)/$',views.LeaveApplyDeleteView.as_view(),name='apply_delete'),
    url(r'status/(?P<status>[0-9A-Za-z_\-]+)/(?P<approve_by>[0-9A-Za-z_\-]+)/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<lidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.status, name='status'),
        url(r'ajax/leave_status/$', views.leave_status,name='leave_status'),
        url(r'api/postings/',include('leave.api.urls', namespace='api-postings')),
]

alms/leave/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
# Create your models here.
class LeaveRules(models.Model):
    leave_type = models.CharField(max_length=256,blank=False)
    leave_rules = models.TextField(blank=True,default='')
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.leave_type
    # @property
    # def owner(self):
    #     return self.user

class LeaveApply(models.Model):
    user = models.ForeignKey(User,related_name='leaves')
    leave_type = models.ForeignKey(LeaveRules,related_name='leaves',null=True,blank=True)
    start_date = models.DateField(default=datetime.date.today, blank=True)
    end_date = models.DateField(default='', blank=True)
    no_of_days = models.DecimalField(max_digits=2,decimal_places=0,null=True)
    notes = models.TextField(blank=True,default='')
    tag_to = models.CharField(max_length=256,blank=False)
    status = models.CharField(max_length=256,default='Awaiting')
    status_by = models.CharField(max_length=256,default='')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.user.username

alms/leave/forms.py
from django import forms
from django.contrib.auth.models import User
from leave.models import LeaveRules,LeaveApply
from django.conf import settings
import datetime
class LeaveRulesForm(forms.ModelForm):
    class Meta():
        model = LeaveRules
        fields = ('leave_type','leave_rules')

        widgets = {
            'leave_rules':forms.Textarea(attrs={'class':'editable'})
            }


class LeaveApplyForm(forms.ModelForm):
    start_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS,widget=forms.DateInput(format='%d/%m/%Y',attrs={'class': 'fromDate'}))
    end_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS,widget=forms.DateInput(format='%d/%m/%Y',attrs={'class': 'toDate'}))
    class Meta():
        model = LeaveApply
        fields = ('leave_type','start_date','end_date','notes','tag_to','no_of_days')

        widgets = {
            'no_of_days':forms.HiddenInput(attrs={'class':'no_of_days'})
            }

alms/leave/api/views.py
from rest_framework import generics,mixins
from leave.models import LeaveRules
from .permissions import IsOwnerOrReadOnly
from .serializers import LeaveRulesSerializer

class LeaveRulesAPIView(mixins.CreateModelMixin,generics.ListAPIView):
    lookup_field = 'pk'
    serializer_class = LeaveRulesSerializer

    def get_queryset(self):
        return LeaveRules.objects.all()

    # def perform_create(self, serializer):
    #     serializer.save(user=self.request.user)

    def post(self,request,*args,**kwargs):
        return self.create(request,*args,**kwargs)
    # def put(self,request,*args,**kwargs):
    #     return self.update(request,*args,**kwargs)
    # def patch(self,request,*args,**kwargs):
    #     return self.update(request,*args,**kwargs)

class LeaveRulesRudView(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = 'pk'
    serializer_class = LeaveRulesSerializer
    # permission_classes = [IsOwnerOrReadOnly]

    def get_queryset(self):
        return LeaveRules.objects.all()

alms/leave/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, DeleteView
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models
from . import forms
from django.utils import timezone
from datetime import datetime
from django.http import HttpResponseForbidden,Http404
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.template.loader import render_to_string
from employee.tokens import account_activation_token

from django.utils.encoding import force_text
from django.contrib.auth.tokens import default_token_generator

from django.core.mail import EmailMessage
from django.http import HttpResponse
import string
from django.http import JsonResponse
from django.db.models import Count

# Create your views here.
class List(LoginRequiredMixin,ListView):
    model = models.LeaveRules
    template_name = 'leave/leave_rules_list.html'

class LeaveRulesDeleteView(DeleteView):
    model = models.LeaveRules
    success_url = reverse_lazy("leave:list")

class LeaveRulesCreateView(LoginRequiredMixin,CreateView):
    form_class = forms.LeaveRulesForm
    template_name = 'leave/leave_rules_form.html'
    success_url = reverse_lazy("leave:list")

class LeaveRulesDetail(LoginRequiredMixin,DetailView):
    model = models.LeaveRules
    template_name = 'leave/leave_rules_detail.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(pk__iexact=self.kwargs.get('pk'))

class LeaveRulesUpdateView(LoginRequiredMixin,UpdateView):
    model = models.LeaveRules
    fields = ('leave_type','leave_rules')
    template_name = 'leave/leave_rules_form.html'
    # success_url = reverse_lazy("leave:detail" pk=leaverules.pk)
    success_url = reverse_lazy("leave:list")

class LeaveApplyCreateView(LoginRequiredMixin,CreateView):
    form_class = forms.LeaveApplyForm
    template_name = 'leave/leave_apply_form.html'
    success_url = reverse_lazy("leave:list")

    def post(self, request, *args, **kwargs):
        registered = False

        if request.method == 'POST':
            leave_form = forms.LeaveApplyForm(data=request.POST)
            draft = request.POST.get('save', False)

            if leave_form.is_valid():
                leave = leave_form.save(commit=False)
                leave.user = request.user
                flag = 1
                if draft != 'Save':
                    leave.published_date = timezone.now()
                    leave.save()
                    flag = leave_send_mails(request,leave.id)
                else:
                    leave.save()
                registered = True
                if flag != 1:
                    return redirect('leave:applied')
                else:
                    return redirect('leave:draft', username=request.user.username)

            else:
                print(leave_form.errors)
        else:
            leave_form = self.form_class

        return render(request,self.template_name,
                                {'form':leave_form,
                                'registered':registered})

class LeaveAppliedListView(LoginRequiredMixin,ListView,BaseException):
    model = models.LeaveApply
    template_name = 'leave/leave_apply_status_list.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return self.model.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
        else:
            raise Http404()

class LeaveAppliedUserListView(LoginRequiredMixin,ListView,BaseException):
    model = models.LeaveApply
    template_name = 'leave/leave_apply_list.html'

    def get_queryset(self):
        if self.kwargs.get('username') == self.request.user.username:
            return self.model.objects.filter(user__username__iexact=self.kwargs.get('username'),published_date__lte=timezone.now()).order_by('-published_date')
        else:
            raise Http404()

class LeaveDraftListView(LoginRequiredMixin,ListView,BaseException):
    model = models.LeaveApply
    template_name = 'leave/leave_apply_list.html'

    def get_queryset(self):
        if self.kwargs.get('username') == self.request.user.username:
            return self.model.objects.filter(user__username__iexact=self.kwargs.get('username'),published_date__isnull=True).order_by('created_date')
        else:
            raise Http404()

class LeaveApplyUpdateView(LoginRequiredMixin,UpdateView):
    model = models.LeaveApply
    fields = ('leave_type','start_date','end_date','notes','tag_to')
    template_name = 'leave/leave_apply_form.html'
    # success_url = reverse_lazy("leave:detail" pk=leaverules.pk)
    success_url = reverse_lazy("leave:applied")

class LeaveApplyDeleteView(LoginRequiredMixin,DeleteView):
    model = models.LeaveApply
    success_url = reverse_lazy("leave:applied")

def leave_send_mails(request,leave_id):
    model = models.LeaveApply
    start_date = datetime.strptime(request.POST['start_date'], '%d/%m/%Y').strftime('%Y-%m-%d')
    end_date = datetime.strptime(request.POST['end_date'], '%d/%m/%Y').strftime('%Y-%m-%d')
    user_leave_history = model.objects.filter(user__username__iexact=request.user.username,published_date__lte=timezone.now()).exclude(pk=leave_id). extra(select={\
        'month': "EXTRACT(month FROM published_date)",
        'year': "EXTRACT(year FROM published_date)",
    }).\
    values('month', 'year').\
    annotate(count_items=Count('published_date')).order_by('-published_date')
    print ("month,count,total")
    total = 0
    for item in user_leave_history:
        total = total + item['count_items']
        if item['year'] < 2018: continue
        print ("%02d-%s,%s,%s" % (item['month'], item['year'], item['count_items'], total))
    others_leave_history = model.objects.filter(published_date__range=(start_date, end_date)).exclude(user__username__iexact=request.user.username).order_by('-published_date')
    superusers = models.User.objects.filter(is_superuser=True)
    recipient_list = request.POST['tag_to']
    for suser in superusers:
        if suser.email not in recipient_list:
            if request.user.email not in suser.email:
                recipient_list += suser.email

    recipient_list = list(set(recipient_list.split(",")))

    current_site = get_current_site(request)
    subject = 'Leave request'

    for rlist in recipient_list:
        if rlist.strip():
            message = render_to_string('leave/leave_request_email.html', {
                'domain': current_site.domain,
                'user': request.user,
                'leave_details': request.POST,
                'user_history': user_leave_history,
                'other_history': others_leave_history,
                'Approved': urlsafe_base64_encode(force_bytes('Approved')).decode(),
                'Declined': urlsafe_base64_encode(force_bytes('Declined')).decode(),
                'uidb64': urlsafe_base64_encode(force_bytes(request.user.pk)).decode(),
                'lidb64': urlsafe_base64_encode(force_bytes(leave_id)).decode(),
                'approve_by': urlsafe_base64_encode(force_bytes(rlist)).decode(),
                'token': default_token_generator.make_token(request.user)
                })
            print(message)
            email = EmailMessage(subject, message, "sathishkumar@appinessworld.com", [rlist])
            email.content_subtype = "html"
            res = email.send()
            return HttpResponse('%s'%res)

def status(request,status,approve_by, uidb64, lidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = models.User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, models.User.DoesNotExist):
        user = None
    try:
        lid = force_text(urlsafe_base64_decode(lidb64))
        leave = models.LeaveApply.objects.get(pk=lid)
    except (TypeError, ValueError, OverflowError, models.LeaveApply.DoesNotExist):
        leave = None
    if user and default_token_generator.check_token(user, token):
        status = force_text(urlsafe_base64_decode(status))
        approved_email = force_text(urlsafe_base64_decode(approve_by))
        status_by = models.User.objects.get(email=approved_email)

        leave.status = status
        leave.status_by = status_by.first_name
        leave.save()
        flag = leave_status_mails(request,user,leave,approved_email)
        validlink = {'validlink':True}
        return render(request, 'leave/leave_status.html',context=validlink)
    else:
        return render(request, 'leave/leave_status.html',{'validlink': False})

def leave_status_mails(request,user,leave,approved_email):
    superusers = models.User.objects.filter(is_superuser=True)
    recipient_list = leave.tag_to
    for suser in superusers:
        if suser.email not in recipient_list:
            if user.email not in suser.email:
                recipient_list += suser.email

    recipient_list += user.email

    recipient_list = list(set(recipient_list.split(",")))

    current_site = get_current_site(request)
    subject = 'Leave status'

    for rlist in recipient_list:
        if rlist.strip():
            if rlist not in approved_email:
                message = render_to_string('leave/leave_status_email.html', {
                    'domain': current_site.domain,
                    'user': user,
                    'leave_details': leave,
                    })
                print(message)
                email = EmailMessage(subject, message, "sathishkumar@appinessworld.com", [rlist])
                email.content_subtype = "html"
                res = email.send()
                return HttpResponse('%s'%res)

def leave_status(request):

alms/leave/templates/leave/_leave_apply_list.html
    <td><strong>{{leave.start_date}}</strong></td>
    <td><strong>{{leave.end_date}}</strong></td>
    <td><strong>{{leave.leave_type}}</strong></td>
    <td><strong>{{leave.notes}}</strong></td>
      {% if user.is_authenticated and leave.user == user %}
        <td><a href="{% url 'leave:apply_update' pk=leave.pk %}"> Edit</a>
          <a href="{% url 'leave:apply_delete' pk=leave.pk %}">delete</a></td>
      {% endif %}

alms/leave/templates/leave/leave_apply_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
{% if user.is_superuser %}
   <form method="post">
     {% csrf_token %}
     {% bootstrap_form form %}
     <p class="count"></p>
     <input type="submit" value="Submit">
     <input type="submit" name="save" value="Save">
   </form>
{% else %}
  <h1>Sorry! you don't have access</h1>
{% endif %}

{% endblock %}
{% block javascript %}
<script>

$(document).ready(function() {
  var hday='';
  var holiday = [];
              $.ajax({
                url: '/holiday/ajax/list/',
                type: 'POST',
                data: {
                },
                // async:false,
                dataType: 'json',
                success: function (data) {
                  if (data == 0) {
                      console.log('Try different country name');
                    } else {
                        $.each(data.list, function (i, item) {
                              var str_array = item.holiday_date.split('-');

                              var dat = str_array[1]+'/'+str_array[2]+'/'+str_array[0];
                              var dt = new Date(dat);
                              hday += dt+',';
                              holiday.push(item);
                            });
                        }
                }
              });
// set default dates
var start = new Date();
// // set end date to max one year period:
var end = new Date(new Date().setYear(start.getFullYear()+1));

    $("#id_start_date").datepicker({
      minDate:start,
      maxDate:end,
      dateFormat: 'dd/mm/yy',
      beforeShowDay: function(date) {
        var string = jQuery.datepicker.formatDate('yy-mm-dd', date);

        if (contains(holiday,string)) {
          // debugger;
          return [false, '']
        } else {
          var day = date.getDay();
          return [(day != 0 && day != 6), ''];
        }
        },
        onSelect: function (selected) {
            var str_array = selected.split('/');
            var dat = str_array[1]+'/'+str_array[0]+'/'+str_array[2];
            var dt = new Date(dat);
            dt.setDate(dt.getDate() + 1);
            $("#id_end_date").datepicker("option", "minDate", dt);
            $(".count").text(1);
            $(".no_of_days").val(1);
        }
    });
    $("#id_end_date").datepicker({
      maxDate:end,
      dateFormat: 'dd/mm/yy',
      beforeShowDay: function(date) {
        var string = jQuery.datepicker.formatDate('yy-mm-dd', date);

        if (contains(holiday,string)) {
          // debugger;
          return [false, '']
        } else {
          var day = date.getDay();
          return [(day != 0 && day != 6), ''];
        }
        },
        onSelect: function (selected) {
            var str_array = selected.split('/');
            var dat = str_array[1]+'/'+str_array[0]+'/'+str_array[2];
            var dt = new Date(dat);
            dt.setDate(dt.getDate() - 1);
            $("#id_start_date").datepicker("option", "maxDate", dt);
            calcBusinessDays();
        }
    });

    function contains(a, obj) {
      var i = Object.keys(a).length;
      while (i--) {
       if (a[i]['holiday_date'] === obj) {
           return true;
       }
    }
    return false;
}

function calcBusinessDays() { // input given as Date objects
  var d1 = $("#id_start_date").val();
  var d2 = $("#id_end_date").val();
  var str_array = d1.split('/');
  var dDate1 = new Date(str_array[1]+'/'+str_array[0]+'/'+str_array[2]);
  var str_array = d2.split('/');
  var dDate2 = new Date(str_array[1]+'/'+str_array[0]+'/'+str_array[2]);
  var oneDay = 24*60*60*1000;
  daysDiff = parseInt((dDate2.getTime()-dDate1.getTime())/oneDay,10)+1;

  if (daysDiff>0) {
  for (var i = dDate1.getTime(), lst = dDate2.getTime(); i <= lst; i += oneDay) {
    var d = new Date(i);
    if (d.getDay() == 6 || d.getDay() == 0 || hday.indexOf(d) != -1) {
        daysDiff--;
    }
  }
}
$(".count").text(daysDiff);
$(".no_of_days").val(daysDiff);
console.log(daysDiff);
}

});

</script>

<script>
 $( function() {
   var option = [];
            $.ajax({
              url: '/employee/ajax/list/',
              type: 'POST',
              data: {
              },
              // async:false,
              dataType: 'json',
              success: function (data) {
                if (data == 0) {
                    console.log('Try different country name');
                  } else {
                      $.each(data.list, function (i, item) {
                            option.push(item.email);
                          });
                      }
              }
            });

   function split( val ) {
     return val.split( /,\s*/ );
   }
   function extractLast( term ) {
     return split( term ).pop();
   }

   $( "#id_tag_to" )
     // don't navigate away from the field on tab when selecting an item
     .on( "keydown", function( event ) {
       if ( event.keyCode === $.ui.keyCode.TAB &&
           $( this ).autocomplete( "instance" ).menu.active ) {
         event.preventDefault();
       }
     })
     .autocomplete({
       minLength: 0,
       source: function( request, response ) {
         // delegate back to autocomplete, but extract the last term
         response( $.ui.autocomplete.filter(
           option, extractLast( request.term ) ) );
       },
       focus: function() {
         // prevent value inserted on focus
         return false;
       },
       select: function( event, ui ) {
         var terms = split( this.value );
         // remove the current input
         terms.pop();
         // add the selected item
         terms.push( ui.item.value );
         // add placeholder to get the comma-and-space at the end
         terms.push( "" );
         this.value = terms.join( ", " );
         return false;
       }
     });
 } );
 </script>
{% endblock %}

alms/leave/templates/leave/leave_apply_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
  <h1>Leave List:
    {% for leave in leaveapply_list|slice:":1"  %}
      {% if leave.published_date %}
        Applied
      {% else %}
        Draft
      {% endif %}
    {% endfor %}</h1>
  <div class="">
    <a href="{% url 'leave:apply'%}">Apply Leave</a>
  </div>

  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Start date</th>
        <th scope="col">End date</th>
        <th scope="col">Leave type</th>
        <th scope="col">Notes</th>
        {% if user.is_authenticated %}
          <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
  {% for leave in leaveapply_list %}
    <tr>
    {% include 'leave/_leave_apply_list.html' %}
    </tr>
  {% endfor %}

  </tbody>
</table>
{% endblock %}

alms/leave/templates/leave/leave_apply_status_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
  <h1>Leave List: Applied</h1>
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Start date</th>
        <th scope="col">End date</th>
        <th scope="col">Leave type</th>
        <th scope="col">Notes</th>
        {% if user.is_superuser %}
          <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>

  {% for leave in leaveapply_list %}
    <tr>
      <td><strong>{{leave.start_date}}</strong></td>
      <td><strong>{{leave.end_date}}</strong></td>
      <td><strong>{{leave.leave_type}}</strong></td>
      <td><strong>{{leave.notes}}</strong></td>
        {% if user.is_superuser %}
          <td><select class="status" name="status">
            {% with 'Awaiting Approved Declined' as list %}
            {% for status in list.split %}
              {% if status in leave.status %}
                <option value="{{status}},{{leave.pk}},{{leave.user.pk}}" selected>{{status}}</option>
              {% else %}
                <option value="{{status}},{{leave.pk}},{{leave.user.pk}}">{{status}}</option>
              {% endif %}
            {% endfor %}
            {% endwith %}

            </select>
          </td>
        {% endif %}
    </tr>
  {% endfor %}

  </tbody>
</table>
{% endblock %}


{% block javascript %}
  <script>
  var flag = 0;
$('select').on('change', function() {

    var approved_email = "{{user.email}}";

      $.ajax({
        url: '/leave/ajax/leave_status/',
        data: {
          'data': $(this).val(),
          'approved_email': approved_email
        },
        async:false,
        dataType: 'json',
        success: function (data) {

        }
      });
  })
  </script>
{% endblock %}

alms/leave/templates/leave/leave_request_email.html
{% autoescape off %}
Hi,
<br/>
 {{ user.first_name }} applied from {{leave_details.start_date}} to {{leave_details.end_date}},
<br/>
 {{ user.first_name }} leave history:
 Total number of days leave on this year(till date): {{ user_history|length }}

 Other's leave applied on same date:
 {% for other in other_history %}
 {{other.username}}
{{other.start_date}}
{{other.end_date}}
{{other.leave_type}}
 {% endfor %}

Please click on the link below to confirm your registration:

Approve: http://{{ domain }}{% url 'leave:status' status=Approved approve_by=approve_by uidb64=uidb64 lidb64=lidb64 token=token %}

Decline: http://{{ domain }}{% url 'leave:status' status=Declined approve_by=approve_by uidb64=uidb64 lidb64=lidb64 token=token %}
{% endautoescape %}

alms/leave/templates/leave/leave_rules_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="">
  {% if user.is_superuser %}
    <a href="{% url 'leave:update' pk=leaverules.pk %}"> Edit</a>
  {% endif %}
</div>

<div class="">
  <h1>{{leaverules.rules}}</h1>
</div>
{% endblock %}

alms/leave/templates/leave/leave_rules_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
{% if user.is_superuser %}
   <form method="post">
     {% csrf_token %}
     {% bootstrap_form form %}
     <input type="submit" value="Submit">
   </form>
{% else %}
  <h1>Sorry! you don't have access</h1>
{% endif %}

{% endblock %}

alms/leave/templates/leave/leave_rules_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
  <h1>Leave Rules</h1>
  <div class="">
    <a href="{% url 'leave:create'%}">Add Rules</a>
  </div>

  {% for leave in leaverules_list %}
  <div class="">
    <div class="">
      <h2><strong>{{leave.leave_type}}</strong></h2>
      <h3><strong>{{leave.leave_rules}}</strong></h3>

      <div class="">
        {% if user.is_superuser %}
          <a href="{% url 'leave:update' pk=leave.pk %}"> Edit</a>
          <a href="{% url 'leave:delete' pk=leave.pk %}">delete</a>
        {% endif %}
      </div>
    </div>
  </div>

  {% endfor %}
{% endblock %}

alms/leave/templates/leave/leave_status.html
{% extends 'base.html' %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  {% if validlink %}
    <h3>Thank you</h3>
  {% else %}
    <p>
      This link was invalid, possibly because it has already been used.
    </p>
  {% endif %}

{% endblock %}

alms/leave/templates/leave/leave_status_email.html
{% autoescape off %}
Hi,
<br/>
 {{ user.first_name }} applied leave from {{leave_details.start_date}} to {{leave_details.end_date}},
<br/>
Status: {{leave_details.status}} by {{leave_details.status_by}}
<br/>
<br/>
 Thank You

{% endautoescape %}

alms/leave/templates/leave/leaveapply_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
    <h1>Delete {{leaveapply.leave_type}}</h1>
    <form method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Delete">
      <a href="{% url 'leave:applied' %}">Cancel</a>

    </form>
{% endblock %}

alms/leave/templates/leave/leaverules_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
    <h1>Delete {{leaverules.leave_type}}</h1>
    <form method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Delete">
      <a href="{% url 'leave:list' %}">Cancel</a>

    </form>
{% endblock %}