cbv/apps/state/urls.py
from django.conf.urls import url
from . import views

app_name = ''

urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(),name='list'),
]

cbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete')
]

cbv/cbv/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view()),
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app')),
    url(r'^state/', include('state.urls',namespace='state')),
]

cbv/apps/state/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str_(self):
        return self.name

cbv/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str_(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})
    
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students')

    def __str__(self):
        return self.name

cbv/apps/state/views.py
from django.shortcuts import render
from django.views.generic import View, ListView
from . import models

# Create your views here.

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

cbv/basic_app/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, DeleteView
from django.views.generic.edit import UpdateView
from . import models

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_details.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    model = models.School
    fields = ('name','principal')
    template_name = 'basic_app/school_form.html'

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

cbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <ul>
        <li> <a href="{% url 'basic_app:list'%}">School</a> </li>
        <li> <a href="{% url 'admin:index' %}">Admin</a> </li>
        <li></li>
      </ul>

    </div>
    <div class="">
      {% block body_block %}

      {% endblock %}

    </div>

  </body>
</html>

cbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html'%}
  {% block body_block %}
    <h1>Delete {{school.name}}</h1>
    <form method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Delete">
      <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>

    </form>
  {% endblock %}

cbv/basic_app/templates/basic_app/school_details.html
{% extends 'basic_app/basic_app_base.html' %}
  {% block body_block %}
    <div class="">
      <h1>Welcome to the School Detail page</h1>
      <h2>Schol details:</h2>
      <p>Name: {{ school_detail.name }}</p>
      <p>principal: {{ school_detail.principal }}</p>
      <p>location: {{ school_detail.location }}</p>
      <h3>Students:</h3>
      {% for student in school_detail.students.all %}
        <p>{{student.name}} who is {{student.age}} years old</p>
      {% endfor %}
    </div>
    <div class="">
      <p> <a href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>

    </div>
  {% endblock%}

cbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
  <h1>
      {% if not form.instance.pk %}
        Create School
      {% else %}

        Update School
      {% endif %}
  </h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">

  </form>
{% endblock %}

cbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
  <h1>Welcome to a list of all the schools!</h1>
  <ol>
    {% for school in schools %}
      <h2> <li><a href="{{school.id}}">{{ school.name }}</a></li> </h2>
    {% endfor %}
  </ol>
{% endblock %}

cbv/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <ul>
        <li> <a href="{% url 'basic_app:list'%}">School</a> </li>
        <li> <a href="{% url 'admin:index' %}">Admin</a> </li>
        <li></li>
      </ul>

    </div>
    <div class="">
      {% block body_block %}

      {% endblock %}

    </div>

  </body>
</html>

cbv/templates/index.html
{% extends 'base.html' %}
  {% block body_block %}
  <h1>Welcome to Home pageTesting</h1>

  {% endblock%}